## Numpy

In [1]:
import numpy as np

In [2]:
# Arreglos
x = np.array([10, 20, 30, 40, 50])
x

array([10, 20, 30, 40, 50])

In [ ]:
# LINSPACE: Retorna listado de números de acuerdo a parámetros dados
y = np.linspace(0, 10, 5)
y

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# Arange: Retorna un listado de números de acuerdo a parámetros (Más óptimo que linspace)
z = np.arange(0, 10, 2)
z

array([0, 2, 4, 6, 8])

In [6]:
# Arreglo de zeros
x = np.zeros((5, 3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# Horizontal y vertical Stack
x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 20, 30, 40, 50])

hs = np.hstack((x, y))
vs = np.vstack((x, y))

print(hs)
print(vs)

[ 1  2  3  4  5 10 20 30 40 50]
[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [8]:
# Rango y dimensión de tensor o arreglo

rango = vs.ndim
dimensiones = vs.shape

print(f"El rango del tensor es {rango} y las dimensiones son {dimensiones}")

El rango del tensor es 2 y las dimensiones son (2, 5)
