## Numpy

In [1]:
import numpy as np

In [2]:
# Arreglos
x = np.array([10, 20, 30, 40, 50])
x

array([10, 20, 30, 40, 50])

In [ ]:
# LINSPACE: Retorna listado de números de acuerdo a parámetros dados
y = np.linspace(0, 10, 5)
y

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# Arange: Retorna un listado de números de acuerdo a parámetros (Más óptimo que linspace)
z = np.arange(0, 10, 2)
z

array([0, 2, 4, 6, 8])

In [6]:
# Arreglo de zeros
x = np.zeros((5, 3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# Horizontal y vertical Stack
x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 20, 30, 40, 50])

hs = np.hstack((x, y))
vs = np.vstack((x, y))

print(hs)
print(vs)

[ 1  2  3  4  5 10 20 30 40 50]
[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [8]:
# Rango y dimensión de tensor o arreglo

rango = vs.ndim
dimensiones = vs.shape

print(f"El rango del tensor es {rango} y las dimensiones son {dimensiones}")

El rango del tensor es 2 y las dimensiones son (2, 5)


### Operaciones con Vectores

In [9]:
v = np.array([1, 2, 3, 4])
w = np.array([5, 6, 7, 8])

In [10]:
# Operaciones se aplican a elemento por elemento, y utilizando el principio de broadcasting
print("suma: ", v + w)
print("resta: ", v - w)
print("suma escalar: ", v + 5)
print("división escalar: ", v / 5)

suma:  [ 6  8 10 12]
resta:  [-4 -4 -4 -4]
suma escalar:  [6 7 8 9]
división escalar:  [0.2 0.4 0.6 0.8]


In [11]:
# Operaciones universales
x = np.array([-2, -1, 0, 1, 2])

print(np.sign(x))
print(np.abs(x))
print(np.sin(x))
print(np.sqrt(x))

[-1 -1  0  1  1]
[2 1 0 1 2]
[-0.90929743 -0.84147098  0.          0.84147098  0.90929743]
[       nan        nan 0.         1.         1.41421356]


/var/folders/84/9lhxzgfs4vg72cmkr47zph8r0000gn/T/ipykernel_72647/2811613947.py:7: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(x))


In [12]:
# Trabajando con NAN (Esto sirve para validar datos o realizar imputaciones)
x = np.array([1, 2, 3, 4, 5])
x_nan = np.array([1, 2, np.nan, 4, np.nan])

print(np.max(x))
print(np.max(x_nan))
print(np.nanmax(x_nan))
print(np.mean(x_nan))
print(np.nanmean(x_nan))

5
nan
4.0
nan
2.3333333333333335


In [13]:
# Posición del valor más grande
print(np.argmax(x))

4


### Reshape

In [14]:
x = np.arange(0, 10, 1)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# El reshape nos ayuda a cambiar la forma que tiene un tensor, esto funciona siempre que se solicite una estructura consistente al arreglo que queremos transformar
np.reshape(x, (2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
### Comparación de performance
# Realizando una regresión lineal

from time import time

x = np.linspace(1, 10000000, 20000000)
b0 = 5
b1 = 2

In [ ]:
# Solución tradicional
y0 = np.empty_like(x)

inicio = time()
for index, value in enumerate(x):
    y0[index] = b0 + b1 * value
fin = time()

print(f"El tiempo de ejecución fué de {fin - inicio}")

El tiempo de ejecución fué de 3.6628921031951904


In [19]:
# Solución con Numpy

x = np.linspace(1, 10000000, 20000000)
b0 = 5
b1 = 2

y = np.ones_like(x).reshape(-1, 1) # Creamos un vector con 'unos' del mismo tamaño de x y lo convertimos a columna con reshape
x = np.reshape(x, (-1, 1)) # Ahora también convertimos a columna el vector x
a = np.hstack([x, y]) # Pegamos el vector 'x' y 'y' elemento por elemento dado que tienen la misma cantidad, esto nos deja un vector columna
betas = np.array(([b1], [b0]))

inicio = time()
y1 = np.matmul(a, betas)
fin = time()

print (f"El tiempo de ejecución fué de {fin - inicio}")

El tiempo de ejecución fué de 0.05666017532348633


In [20]:
# Vectorizar funciones

def foo(x, param): 
    if (x <= param):
        return -1
    else:
        return 1


x = np.arange(0, 10, 1)
vectFoo = np.vectorize(foo)

vectFoo(x, 5)

array([-1, -1, -1, -1, -1, -1,  1,  1,  1,  1])

In [21]:
# Validar NANs o Null en arreglo
x = np.array([1, 2, 3, np.nan, 5])
np.isnan(x)

array([False, False, False,  True, False])